* Generated by CDO operator gradsdes
*
DSET  ^ERA5_SFC_msl_%y4_r480x241_day.EA.nc
OPTIONS template
OPTIONS 365_day_calendar
DTYPE  NetCDF
XDEF 281 LINEAR 90.000000 0.750000
YDEF 81 LINEAR -30.000000 0.750000
ZDEF 1 LEVELS 0 
TDEF 5475 LINEAR 00:00Z01jan2005 1dy
TITLE  ERA5_SFC_msl_2011_r480x241_day.EA.nc  281x81 grid
UNDEF  -32767
VARS  1
msl                0  t,y,x  Mean sea level pressure  [Pa]
ENDVARS
