* Generated by CDO operator gradsdes
*
DSET  ^sst.day.mean.%y4.nc
OPTIONS template
OPTIONS 365_day_calendar
DTYPE  NetCDF
XDEF 1440 LINEAR 0.125000 0.250000
YDEF 720 LINEAR -89.875000 0.250000
ZDEF 1 LEVELS 0 
TDEF 5475 LINEAR 00:00Z01jan2005 1dy
TITLE  sst.day.mean.2005.nc  1440x720 grid
UNDEF  -9.96921e+36
VARS  1
sst                0  t,y,x  Daily Sea Surface Temperature  [degC]
ENDVARS
